### ISSUE TITLE
🐧 An xkcd Adventure ↔ v23.6.0

### ISSUE THREAD

**Issue by kamaradclimber** [itchio/itch-compatibility-watchlist#1274]
:rotating_light: game [An xkcd Adventure](https://moonlock.itch.io/an-xkcd-adventure) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/bee1a748ca3531da68bebd4e0598bd69).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Oh fun, that's a text game, and it's even kinda launched correctly:

```
[2017-11-21 @ 11:38:00.188] [launch/native] out: 
[2017-11-21 @ 11:38:00.189] [launch/native] out: Welcome to an xkcd adventure.
[2017-11-21 @ 11:38:00.189] [launch/native] out: You are locked out of your apartment.  
[2017-11-21 @ 11:38:00.189] [launch/native] out: If you had a laptop, you could ssh into your Mac and use the speech synth 
[2017-11-21 @ 11:38:00.189] [launch/native] out: to tell her what happened.  Maybe someone will let you borrow theirs.
[2017-11-21 @ 11:38:00.189] [launch/native] out: 
[2017-11-21 @ 11:38:00.189] [launch/native] out: Type 'help' for a list of commands.
[2017-11-21 @ 11:38:00.189] [launch/native] out: 
[2017-11-21 @ 11:38:00.190] [launch/native] err: Traceback (most recent call last):
[2017-11-21 @ 11:38:00.190] [launch/native] err:   File "/home/grego/.config/itch/apps/An xkcd Adventure/xkcd.py", line 2, in <module>
[2017-11-21 @ 11:38:00.190] [launch/native] err:     from src import main
[2017-11-21 @ 11:38:00.190] [launch/native] err:   File "/home/grego/.config/itch/apps/An xkcd Adventure/src/main.py", line 98, in <module>
[2017-11-21 @ 11:38:00.190] [launch/native] err:     command = input(">> ").split(" ")
[2017-11-21 @ 11:38:00.190] [launch/native] err: EOFError: EOF when reading a line
[2017-11-21 @ 11:38:00.190] [launch/native] out: >> 
```

Unfortunately command-line linux games aren't supported yet!
