### ISSUE TITLE
🐧 Galimulator ↔ v18.7.0

### ISSUE THREAD

**Issue by clayote** [itchio/itch-compatibility-watchlist#147]
:rotating_light: game [Galimulator](https://snoddasmannen.itch.io/galimulator) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/fbd552a6adc6f3ee26edf5c3944f26bb).

:running:  I used the itch desktop app to install the jar version of Galimulator, and it won't launch from inside the app. I do have Java installed, and I can ​run Galimulator by changing to the galimulator-jar directory in a terminal and running `java -jar galimulator-desktop.jar` -- and it seems like the itch app should be able to do that, but no.

**Comment by fasterthanlime** [comment]
What happens if you run `java -jar /home/zachary/.config/itch/apps/Galimulator/galimulator-jar/galimulator-desktop.jar` in a terminal from a different directory? (ie. not the game's directory).

**Comment by clayote** [comment]
```
Exception in thread "main" java.lang.RuntimeException: Error packing images.
    at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:635)
    at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:618)
    at com.example.Main.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Input file does not exist: /home/sanotehu/data/sprites
    at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:117)
    at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:70)
    at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:633)
    ... 2 more
```

**Comment by clayote** [comment]
Maybe this log that the itch app produced will be more helpful.

```
[2016-09-16 @ 19:14:35.195] [tasks/launch] itch 18.9.0 launching game 71252: Galimulator
[2016-09-16 @ 19:14:35.196] [tasks/launch] looking for manifest @ "/home/sanotehu/.config/itch/apps/Galimulator/.itch.toml"
[2016-09-16 @ 19:14:35.197] [tasks/launch] No manifest found (no '.itch.toml' file in top-level directory). Proceeding with heuristics.
[2016-09-16 @ 19:14:35.204] [tasks/launch/native] cave location: "appdata/Galimulator"
[2016-09-16 @ 19:14:35.206] [tasks/launch/native] no manifest action picked
[2016-09-16 @ 19:14:35.207] [launch/poker] initial candidate set: [
  {
    "path": "galimulator-jar/galimulator-desktop.jar"
  }
]
[2016-09-16 @ 19:14:35.210] [launch/poker] candidates after poking: [
  {
    "path": "galimulator-jar/galimulator-desktop.jar",
    "weight": 10559365,
    "score": 95,
    "depth": 2
  }
]
[2016-09-16 @ 19:14:35.212] [launch/poker] candidates after sorting: [
  {
    "path": "galimulator-jar/galimulator-desktop.jar",
    "weight": 10559365,
    "score": 95,
    "depth": 2
  }
]
[2016-09-16 @ 19:14:35.212] [tasks/launch/native] launching .jar, this will fail if no system JRE is installed
[2016-09-16 @ 19:14:35.212] [tasks/launch/native] executing 'java' on 'linux' with args '-jar /home/sanotehu/.config/itch/apps/Galimulator/galimulator-jar/galimulator-desktop.jar'
[2016-09-16 @ 19:14:35.213] [tasks/launch/native] no app isolation
[2016-09-16 @ 19:14:35.213] [tasks/launch/native] spawn command: "java" "-jar" "/home/sanotehu/.config/itch/apps/Galimulator/galimulator-jar/galimulator-desktop.jar"
[2016-09-16 @ 19:14:35.214] [tasks/launch/native] working directory: .
[2016-09-16 @ 19:14:35.215] [tasks/launch/native] command: java
[2016-09-16 @ 19:14:35.216] [tasks/launch/native] args: [
  "-jar",
  "/home/sanotehu/.config/itch/apps/Galimulator/galimulator-jar/galimulator-desktop.jar"
]
[2016-09-16 @ 19:14:35.216] [tasks/launch/native] env keys: []
[2016-09-16 @ 19:14:35.732] [tasks/launch/native] err: Exception in thread "main" java.lang.RuntimeException: Error packing images.
[2016-09-16 @ 19:14:35.733] [tasks/launch/native] err:  at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:635)
[2016-09-16 @ 19:14:35.733] [tasks/launch/native] err:  at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:618)
[2016-09-16 @ 19:14:35.733] [tasks/launch/native] err:  at com.example.Main.main(Unknown Source)
[2016-09-16 @ 19:14:35.733] [tasks/launch/native] err: Caused by: java.lang.IllegalArgumentException: Input file does not exist: /home/sanotehu/src/pointless-xcompose/data/sprites
[2016-09-16 @ 19:14:35.734] [tasks/launch/native] err:  at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:117)
[2016-09-16 @ 19:14:35.734] [tasks/launch/native] err:  at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:70)
[2016-09-16 @ 19:14:35.734] [tasks/launch/native] err:  at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:633)
[2016-09-16 @ 19:14:35.734] [tasks/launch/native] err:  ... 2 more
[2016-09-16 @ 19:14:35.752] [tasks/launch] error while launching 3cf7b1a3-8d88-4172-b241-2959a701df3c: Crash: application crashed. process exited with code 1
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:289:11
From previous event:
    at doSpawn (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:62:18)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:239:13
From previous event:
    at launch (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:358:17)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch.js:293:11
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at doStart (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:235:18)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch.js:74:18
    at next (native)
From previous event:
    at start (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:437:17)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/start-task.js:53:20
    at next (native)
From previous event:
    at startTask (/usr/lib/itch/resources/app.asar/app/reactors/tasks/start-task.js:67:17)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/queue-game.js:100:23
    at next (native)
From previous event:
    at startCave (/usr/lib/itch/resources/app.asar/app/reactors/tasks/queue-game.js:123:18)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/queue-game.js:25:11
    at next (native)
From previous event:
    at queueGame (/usr/lib/itch/resources/app.asar/app/reactors/tasks/queue-game.js:94:17)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (/usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/usr/lib/itch/resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/usr/lib/itch/resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/usr/lib/itch/resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
[2016-09-16 @ 19:14:35.766] [tasks/launch] crashed with application crashed. process exited with code 1
[2016-09-16 @ 19:14:35.767] [tasks/launch] Crash: application crashed. process exited with code 1
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:289:11
From previous event:
    at doSpawn (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:62:18)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch/native.js:239:13
From previous event:
    at launch (/usr/lib/itch/resources/app.asar/app/tasks/launch/native.js:358:17)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch.js:293:11
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at doStart (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:235:18)
    at /usr/lib/itch/resources/app.asar/appsrc/tasks/launch.js:74:18
    at next (native)
From previous event:
    at start (/usr/lib/itch/resources/app.asar/app/tasks/launch.js:437:17)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/start-task.js:53:20
    at next (native)
From previous event:
    at startTask (/usr/lib/itch/resources/app.asar/app/reactors/tasks/start-task.js:67:17)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/queue-game.js:100:23
    at next (native)
From previous event:
    at startCave (/usr/lib/itch/resources/app.asar/app/reactors/tasks/queue-game.js:123:18)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/tasks/queue-game.js:25:11
    at next (native)
From previous event:
    at queueGame (/usr/lib/itch/resources/app.asar/app/reactors/tasks/queue-game.js:94:17)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (/usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/usr/lib/itch/resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/usr/lib/itch/resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/usr/lib/itch/resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
[2016-09-16 @ 19:14:35.770] [diego] diego here, looking around
Linux sanotehu-MacBookPro 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
model name  : Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
model name  : Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:    18
Codename:   sarah
02:00.0 VGA compatible controller: NVIDIA Corporation G96M [GeForce 9600M GT] (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation C79 [GeForce 9400M] (rev b1)
diego out
```

**Comment by fasterthanlime** [comment]
Sorry I haven't replied earlier: this is a bug of the game — it shouldn't rely on the current working directory, but [should load resources relative to the .jar file instead](http://stackoverflow.com/questions/3627426/loading-a-file-relative-to-the-executing-jar-file).

We can probably work around it in the app, but the game should really be fixed.

**Comment by Snoddasmannen** [comment]
Thanks a bunch for the help guys, easy fix for once :) Game will be fixed in the next update.

**Comment by fasterthanlime** [comment]
Awesome, closing this then!
