### ISSUE TITLE
🐧 Superpowers ↔ v18.7.0

### ISSUE THREAD

**Issue by Xananax** [itchio/itch-compatibility-watchlist#180]
:rotating_light: tool [Superpowers](https://sparklinlabs.itch.io/superpowers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b2596293344962f7fcbaf4fbb327db7c).

:running: Gave me this error on launch:

```
Uncaught Exception:
Error: EXDEV: cross-device link not permitted, rename '/home/xananax/.local/share/Superpowers' -> '/hawm/.back/.config/Superpowers'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at Object.getPaths [as default] (/hawm/.back/.config/itch/apps/Superpowers/superpowers-v2.0.0-linux-x64/resources/app/getPaths.js:49:16)
    at EventEmitter.onAppReady (/hawm/.back/.config/itch/apps/Superpowers/superpowers-v2.0.0-linux-x64/resources/app/main.js:52:23)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Both '/' and '/hawm' are EXT4 drives, but they are two different (physical) drives, I suppose that's where the error comes from.
I don't believe it's itch-related, but I'm following the procedure is all.

[Cross reference issue on superpowers](https://github.com/superpowers/superpowers-app/issues/52)

**Comment by fasterthanlime** [comment]
Correct, that doesn't seem itch-related! Having the log here is probably helpful to @elisee & team, but closing nevertheless.

Thanks for the complete report btw! 🌠
