### ISSUE TITLE
🍎 Tube Tycoon ↔ v18.6.0

### ISSUE THREAD

**Issue by ilikealotgithub1234** [itchio/itch-compatibility-watchlist#75]
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/062ba7492e0baac7a5dff22863dc836e).

:running: Any additional details can go here!

**Comment by ilikealotgithub1234** [comment]
[2016-08-10 @ 20:01:41.232] [tasks/launch] reconfiguring because of problem with cave: game.install.no_executables_found
[2016-08-10 @ 20:01:41.296] [tasks/launch] crashed with game.install.could_not_launch (game.install.no_executables_found)
[2016-08-10 @ 20:01:41.296] [tasks/launch] Error: game.install.could_not_launch (game.install.no_executables_found)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:143:17
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback](timers.js:523:5)
From previous event:
    at doStart (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:196:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:72:18
    at next (native)
From previous event:
    at start (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:394:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/start-task.js:53:20
    at next (native)
From previous event:
    at startTask (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/start-task.js:67:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:100:23
    at next (native)
From previous event:
    at startCave (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:123:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:25:11
    at next (native)
From previous event:
    at queueGame (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:94:17)
From previous event:
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/Applications/itch.app/Contents/Resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
[2016-08-10 @ 20:01:41.297] [diego] diego here, looking around
Darwin 142857.home 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
Hardware:

```
Hardware Overview:

  Model Name: MacBook Air
  Model Identifier: MacBookAir6,2
  Processor Name: Intel Core i5
  Processor Speed: 1.4 GHz
  Number of Processors: 1
  Total Number of Cores: 2
  L2 Cache (per Core): 256 KB
  L3 Cache: 3 MB
  Memory: 4 GB
  Boot ROM Version: MBA61.0099.B22
  SMC Version (system): 2.13f15
  Serial Number (system): C02MLNZVG086
  Hardware UUID: C1BAECE5-5876-5943-86DA-95B1D0F2BC0A
```

Graphics/Displays:

```
Intel HD Graphics 5000:

  Chipset Model: Intel HD Graphics 5000
  Type: GPU
  Bus: Built-In
  VRAM (Dynamic, Max): 1536 MB
  Vendor: Intel (0x8086)
  Device ID: 0x0a26
  Revision ID: 0x0009
  Displays:
    Color LCD:
      Display Type: LCD
      Resolution: 1440 x 900
      Pixel Depth: 32-Bit Color (ARGB8888)
      Main Display: Yes
      Mirror: Off
      Online: Yes
      Built-In: Yes
```

diego out

[2016-08-10 @ 20:02:31.579] [tasks/launch] reconfiguring because of problem with cave: game.install.no_executables_found
[2016-08-10 @ 20:02:31.631] [tasks/launch] crashed with game.install.could_not_launch (game.install.no_executables_found)
[2016-08-10 @ 20:02:31.631] [tasks/launch] Error: game.install.could_not_launch (game.install.no_executables_found)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:143:17
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback](timers.js:523:5)
From previous event:
    at doStart (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:196:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:72:18
    at next (native)
From previous event:
    at start (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:394:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/start-task.js:53:20
    at next (native)
From previous event:
    at startTask (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/start-task.js:67:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:100:23
    at next (native)
From previous event:
    at startCave (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:123:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:25:11
    at next (native)
From previous event:
    at queueGame (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:94:17)
From previous event:
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/Applications/itch.app/Contents/Resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
[2016-08-10 @ 20:02:31.631] [diego] diego here, looking around
Darwin 142857.home 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
Hardware:

```
Hardware Overview:

  Model Name: MacBook Air
  Model Identifier: MacBookAir6,2
  Processor Name: Intel Core i5
  Processor Speed: 1.4 GHz
  Number of Processors: 1
  Total Number of Cores: 2
  L2 Cache (per Core): 256 KB
  L3 Cache: 3 MB
  Memory: 4 GB
  Boot ROM Version: MBA61.0099.B22
  SMC Version (system): 2.13f15
  Serial Number (system): C02MLNZVG086
  Hardware UUID: C1BAECE5-5876-5943-86DA-95B1D0F2BC0A
```

Graphics/Displays:

```
Intel HD Graphics 5000:

  Chipset Model: Intel HD Graphics 5000
  Type: GPU
  Bus: Built-In
  VRAM (Dynamic, Max): 1536 MB
  Vendor: Intel (0x8086)
  Device ID: 0x0a26
  Revision ID: 0x0009
  Displays:
    Color LCD:
      Display Type: LCD
      Resolution: 1440 x 900
      Pixel Depth: 32-Bit Color (ARGB8888)
      Main Display: Yes
      Mirror: Off
      Online: Yes
      Built-In: Yes
```

diego out

[2016-08-10 @ 20:03:23.316] [tasks/launch] reconfiguring because of problem with cave: game.install.no_executables_found
[2016-08-10 @ 20:03:23.390] [tasks/launch] crashed with game.install.could_not_launch (game.install.no_executables_found)
[2016-08-10 @ 20:03:23.391] [tasks/launch] Error: game.install.could_not_launch (game.install.no_executables_found)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:143:17
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback](timers.js:523:5)
From previous event:
    at doStart (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:196:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/tasks/launch.js:72:18
    at next (native)
From previous event:
    at start (/Applications/itch.app/Contents/Resources/app.asar/app/tasks/launch.js:394:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/start-task.js:53:20
    at next (native)
From previous event:
    at startTask (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/start-task.js:67:17)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:100:23
    at next (native)
From previous event:
    at startCave (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:123:18)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/tasks/queue-game.js:25:11
    at next (native)
From previous event:
    at queueGame (/Applications/itch.app/Contents/Resources/app.asar/app/reactors/tasks/queue-game.js:94:17)
From previous event:
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/Applications/itch.app/Contents/Resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/Applications/itch.app/Contents/Resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/Applications/itch.app/Contents/Resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Applications/itch.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
[2016-08-10 @ 20:03:23.391] [diego] diego here, looking around
Darwin 142857.home 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
Hardware:

```
Hardware Overview:

  Model Name: MacBook Air
  Model Identifier: MacBookAir6,2
  Processor Name: Intel Core i5
  Processor Speed: 1.4 GHz
  Number of Processors: 1
  Total Number of Cores: 2
  L2 Cache (per Core): 256 KB
  L3 Cache: 3 MB
  Memory: 4 GB
  Boot ROM Version: MBA61.0099.B22
  SMC Version (system): 2.13f15
  Serial Number (system): C02MLNZVG086
  Hardware UUID: C1BAECE5-5876-5943-86DA-95B1D0F2BC0A
```

Graphics/Displays:

```
Intel HD Graphics 5000:

  Chipset Model: Intel HD Graphics 5000
  Type: GPU
  Bus: Built-In
  VRAM (Dynamic, Max): 1536 MB
  Vendor: Intel (0x8086)
  Device ID: 0x0a26
  Revision ID: 0x0009
  Displays:
    Color LCD:
      Display Type: LCD
      Resolution: 1440 x 900
      Pixel Depth: 32-Bit Color (ARGB8888)
      Main Display: Yes
      Mirror: Off
      Online: Yes
      Built-In: Yes
```

diego out
